version: '3.8'

services:
  client:
    build: .
    container_name: genify-client
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5001
    networks:
      - genify-network

networks:
  genify-network:
    external: true 